spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      password: password
  profiles:
    active: native

server:
  port: 8888

