version: '3.9'

services:
  config:
    image: config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      start_period: 15s
    ports:
      - 8888:8888

  registry:
    image: registry
    depends_on:
      config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      start_period: 15s
    ports:
      - 8761:8761

  monitoring:
    image: monitoring
    depends_on:
      registry:
        condition: service_healthy
    ports:
      - 9295:9295

  gateway:
    image: gateway
    depends_on:
      - monitoring
    ports:
      - 9191:9191

  mongodb:
    image: mongo
    depends_on:
      - gateway
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  base-service:
    image: base-service
    depends_on:
      - mongodb
    ports:
      - 8081:8081

  image-service:
    image: image-service
    depends_on:
      - mongodb
    ports:
      - 8082:8082

  location-service:
    image: location-service
    depends_on:
      - mongodb
    ports:
      - 8083:8083

  advert-service:
    image: advert-service
    depends_on:
      - mongodb
    ports:
      - 8085:8085