server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: BASE-SERVICE
          uri: lb://BASE-SERVICE
          predicates:
            - Path=/api/base-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: BASE-SERVICE
                fallbackuri: forward:/baseServiceFallBack
        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/api/image-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: IMAGE-SERVICE
                fallbackuri: forward:/imageServiceFallBack
        - id: ADVERT-SERVICE
          uri: lb://ADVERT-SERVICE
          predicates:
            - Path=/api/advert-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: ADVERT-SERVICE
                fallbackuri: forward:/advertServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream