apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  ports:
    - name: account-service-port
      port: 8084
      targetPort: 8084
  selector:
    app: account-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: zhurasique/account-service:0.1
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: configmap