apiVersion: v1
kind: Service
metadata:
  name: advert-service
spec:
  ports:
    - name: advert-service-port
      port: 8085
      targetPort: 8085
  selector:
    app: advert-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advert-service
  template:
    metadata:
      labels:
        app: advert-service
    spec:
      containers:
        - name: advert-service
          image: zhurasique/advert-service:0.1
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: configmap