apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  ports:
    - name: base-service-port
      port: 8081
      targetPort: 8081
  selector:
    app: base-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-service
  template:
    metadata:
      labels:
        app: base-service
    spec:
      containers:
        - name: base-service
          image: zhurasique/base-service:0.1
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: configmap