apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  ports:
    - name: config-port
      port: 8888
      targetPort: 8888
  selector:
    app: config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: zhurasique/config:0.1
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: configmap