apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - name: gateway-port
      port: 9191
      targetPort: 9191
  selector:
    app: gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: zhurasique/gateway:0.1
          ports:
            - containerPort: 9191
          envFrom:
            - configMapRef:
                name: configmap