apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  ports:
    - name: image-service-port
      port: 8082
      targetPort: 8082
  selector:
    app: image-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: zhurasique/image-service:0.1
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: configmap