apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  ports:
    - name: monitoring-port
      port: 9295
      targetPort: 9295
  selector:
    app: monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: zhurasique/monitoring:0.1
          ports:
            - containerPort: 9295
          envFrom:
            - configMapRef:
                name: configmap