apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
    - name: registry-port
      port: 8761
      targetPort: 8761
  selector:
    app: registry

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: zhurasique/registry:0.1
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: configmap