server:
  port: 9296

spring:
  application:
    name: SERVER-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhurasique/easycar
          clone-on-start: true