hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

server:
  port: 9191
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth:
      path: /uaa/**
      url: http://auth:8800
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:

    base-service:
      path: /api/v1/base/**
      serviceId: base-service
      stripPrefix: false
      sensitiveHeaders:

    image-service:
      path: /api/v1/image/**
      serviceId: image-service
      stripPrefix: false
      sensitiveHeaders:

    advert-service:
      path: /api/v1/advert/**
      serviceId: advert-service
      stripPrefix: false
      sensitiveHeaders:
